AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AGIntegrated Serverless Application

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs10.x
    Handler: index.handler
    Layers:
      - !Ref DependenciesLayer
      - !Ref ServicesLayer
  
Resources:
  # Queues
  OnSiteUsersQueue:
    Type: AWS::SQS::Queue

  # Microservices
  OnSiteUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CropRotationsFunction
      CodeUri: OnSiteUsers/
      Events:
        OnSiteUsersEvent:
          Type: Schedule
          Properties:
            Schedule: rate(60 minute)

  FilesURIsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AssessmentFunction
      CodeUri: FilesURIs/
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OnSiteUsersQueue.Arn
            BatchSize: 10

  ProcessFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AssessmentFunction
      CodeUri: ProcessFiles/

  DownloadFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SoilCharacteristicsFunction
      CodeUri: DownloadFiles/

  GenericDeadLetterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SoilCharacteristicsFunction
      CodeUri: GenericDeadLetter/

  # Layers
  # Layer 1: Dependencies
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependencies
      Description: Node Dependencies
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs10.x
      RetentionPolicy: Retain

  # Layer 2: Services
  ServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: services
      Description: App builder, routing, services injection, configurations
      ContentUri: services/
      CompatibleRuntimes:
        - nodejs10.x
      RetentionPolicy: Retain


 
  # # CloudWatch
  # AlarmTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #     - Protocol: email
  #       Endpoint: !Ref NotificationEmail

  # Alarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmActions:
  #       - !Ref AlarmTopic
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Dimensions:
  #       - Name: FunctionName
  #         Value: !Ref OnSiteUsersFunction
  #     EvaluationPeriods: 1
  #     MetricName: Errors
  #     Namespace: AWS/Lambda
  #     Period: 60
  #     Statistic: Sum
  #     Threshold: '1'
      

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
