version: 0.2

phases:
  install:
    runtime-versions:
         nodejs: 10
    commands:
      - npm install
      - npm run build 
      - zip -r dist.zip ./dist
      - aws cloudformation package --template-file ./LambdaWithQueueTemplate.yaml --s3-bucket $ARTIFACT_S3_BUCKET --s3-prefix $BUCKET_PATH --output-template-file outputtemplate.yaml
      - echo $RUNTIME

artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml